<style lang="scss" scoped>
    @import 'styles.scss';
</style>

<template>
    <div>
        <div class="title">
            <div>{{ names[0] }}\</div>
            <div>\{{ names[1] }}</div>
        </div>
        <div class="paper paper--article">
            <div class="paper__half">
<img src="../../assets/images/heroes/hardy.png">
<p><b>Оливер Харди</b> (18 января 1892 — 7 августа 1957) — аме&shy;риканский комедийный актёр, став&shy;ший извест&shy;ным благо&shy;даря комическому дуэту Лорел и Харди, в котором он выступал более 30 лет.</p>
<p><b>Юные годы</b><br>
Норвел Харди появился на све­­­т 18 января 1892 года в небольшом городе Гарлем в штате Джорджия. Его отец, Оливер Харви, был ветераном Гражданской войны в США, участником сражения при Энтитеме, а мать, Эмили Норвел, была представительницей старейшей семьи в штате, а среди её предков был капитан Хью Норвел, участвовавший ещё в колониальных войнах в XVIII веке. Норвел был самым младшим из пяти детей в семье, а менее чем через год после его рождения, глава семейства умер.
Смерть отца всё же не оставила семью без средств к существованию, так как их мать была успешной владелицей отеля. Будучи ещё мальчишкой, Норвел был отправлен в военную академию в соседний город Милледжвилль, где пробыл до 13 лет. В 1905 году он поступил в методистский колледж в город Янг-Харрис на севере Джорджии, где получил среднее образование. Интереса к получению знаний он не испытывал, зато с юных лет увлекался музыкой и театром. Его мать поддерживала увлечения сына и отправила его в школу-интернат в Атланту, чтобы изучать пение и музыку. Но Норвел часто пропускал занятие и в итоге сбежал из школы и присоединился к странствующей театральной группе. Где-то в 1910 году, в знак уважения к отцу, Норвел прибавил к своему имени имя Оливер, став именоваться Оливер Норвел Харви, а впоследствии и вовсе стал использовать имя отца как собственное.
После недолгого участия в театральной группе Оливер вернулся в Милледжвилль, где устроился на работу в недавно открывшийся кинотеатр, в котором совмещал обязанности киномеханика, билетёра, менеджера и дворника. Вскоре он стал одержим киноиндустрией и решил, что может намного лучше сыграть в кино, чем это ­­­делают увиденные им актёры. По совету друга в 1913 году он переехал в город Джэксонвилл в штат Флорида, где стал в ночное время петь в водевилях в кабаре и ночных клубах, а днём проводил время на местной киностудии «Lubin Studios». Там он познакомился с пианисткой Маделин Салошин, которая в 1913 году стала его первой супругой.</p>
<p><b>Начало кинокарьеры</b><br>
Его кинодебют состоялся год спустя на этой же студии в комедийном немом фильме «Перехитрить папу», где он значился под именем О. Н. Харди. Только в 1914 году Харди появился почти что в 40 кинокартинах. Из-за своего высокого роста и большого веса ему доставался лишь ограниченный круг ролей. Наиболее часто он играл толстяков или злодеев в комедийных фильмах, где его крупные габариты лишь дополняли его образы. После не менее плодотворного 1915 года Харди переехал в Нью-Йорк, где стал сниматься на киностудиях «Pathé», «Casino» и «Edison Studios».
По возвращении в Джэксонвилл Харди уже не вернулся на «Lubin», а стал сотрудничать со студиями «Vim» и «King Bee studios». Там он часто снимался вместе с Чарли Чаплином, при этом во многом подражая комику Эрику Кэмпбеллу, с которым Чаплин сотрудничал годом ранее. После переезда в Лос-Анджелес в 1917 году Оливер Харди стал работать сразу на нескольких независимых голливудских студиях. В том же году он снялся в комедии Брончо Билли Андерсона «Пёс-талисман», где его коллегой по экрану впервые стал Стэн Лорел. Всё же их знаменитый дуэт образовался позже, а после 1917 они не снимались вместе несколько лет.
С 1918 по 1923 год Харди работал на киностудии «Vitagraph», где также играл комедийные роли толстяков в компании с актёром Ларри Симонном. В 1919 году он разошёлся со своей женой, а в 1920 году был оформлен официальный развод, якобы из-за неверности Харди. Уже через год он вновь связал себя узами брака с актрисой Миртл Ривз.</p>
<p><b>Лорел и Харди</b><br>
В 1925 году он вновь встретился со Стэном Лорелом на киностудии «Hal Roach Studios», где тот был режиссёром фильма «Да, да, Нанетт!», и где Харди в свою очередь исполнил одну из ролей. Их тесное сотрудничество началось в 1927 году со съёмок в фильмах «Утиный суп» и «Скользкие жёны». Режиссёр студии «Hal Roach Studios» Лео МакКэри заметил большой интерес аудитории к совместным работам Харди и Лорела и в дальнейшем стал умышленно снимать их вместе, что в итоге к концу того же года привело к появлению дуэта под названием Лорел и Харди, ставшего, возможно, одним из самых известных комических дуэтов в истории кино.
Вслед за этим последовало множество новых совместных комедий, среди которых «Рано в кровать» (1928), «Доходное дело» (1929), «Идеальный день» (1929), «Ещё одна хорошая путаница» (1930), «Будь больше!» (1931), «Украденные драгоценности» (1931) и множество других кинокомедий. Их первая комедия, снятая в цвете, вышла на экраны в 1930 году и называлась «Песня мошенника», а год спустя они впервые появились в полнометражном фильме «Простите нас», хотя вплоть до 1935 года продолжали появляться и в короткометражках. Их наивысшим достижением стала комедия «Музыкальная шкатулка», которая в 1932 году принесла Лорелу и Харди премию «Оскар» в новой номинации «Лучший короткометражный комедийный фильм».</p>
<p><b>Лорел и Харди в программе «USO»</b><br>
Несмотря на такой творческий успех, в личной жизни Оливера Харди было не всё гладко. Его жена Миртл Ривз стала жертвой алкоголизма, из-за чего в 1937 году их пара распалась. После перезаключения контракта с Холом Роучем Лорел и Харди оказались на студии «General Services Studio», где в 1939 году появились вместе в успешной комедии «Летающая парочка». На съёмках этой картины Оливер Харди познакомился со сценаристкой Вирджинией Люсиль Джонс, которая год спустя стала его супругой, и они прожили в счастливом браке 17 лет.
Со вступлением США во Вторую мировую войну в декабре 1941 года в стране появляется организация «USO», которая стала заниматься организацией развлекательных программ и концертов для военнослужащих союзных войск. Основными артистами там были знаменитые американские звёзды, в том числе и Лорел с Харди. Они выступали перед солдатами с различными комическими номерами, в большинстве своём в Великобритании.</p>
<p><b>Спад популярности</b><br>
В то же время они окончательно покинули студию Хола Роуча и стали сниматься на таких крупных кинокомпаниях, как «20th Century Fox» и «MGM». Несмотря на больший коммерческий успех этих фильмов, их художественная особенность оставляла желать лучшего, что в итоге привело к спаду их популярности. К концу 1940-х годов они почти совсем перестали появляться на большом экране, а в 1947 году отправились в гастрольный шестинедельный тур по Великобритании. Из-за большого успеха, который сопровождал их во время всех выступлений, их тур растянулся на несколько лет, включив в себя страны Скандинавии, Бельгию и Францию, а затем вновь Великобританию.</p>
<p><b>Лорел и Харди в фильме «Утопия»</b><br>
В 1949 году друг Оливера Харди, также знаменитый актёр Джон Уэйн, убедил его вернуться на большой экран, пригласив его в фильм «Боец из Кентукки», где он сам играл главную роль. Год спустя, уже по настоянию Фрэнка Капры, Оливер Харди снялся в небольшой роли в его фильме «Стремясь высоко» с Бингом Кросби в главной роли. В 1951 году Лорел и Харди в последний раз появились вместе на большом экране в совместной французско-итальянской комедии «Атолл К» (в американском прокате — «Утопия»), которая по многим пунктам уступала их прежним совместным проектам и не принесла им большого успеха. В 1955 году они заключили контракт с Холом Роучем-мл. на съёмки телевизионного комедийного шоу, но из-за инсульта Лорела, после которого он долго не мог оправиться, и проблем со здоровьем самого Харди этот проект так и не был реализован.</p>
<p><b>Последние годы</b><br>
После сердечного приступа, который Оливер Харди перенёс в мае 1954 года, он стал предельно чётко следить за своим здоровьем. За последующие пару месяцев он сбросил почти 70 кг веса, став при этом совершенно другим человеком, в котором тяжело было узнать прежнего толстяка Оливера Харди. В своих письмах к Лорелу он сообщал ему о том, что возможно болен раком, что, скорее всего и стало причиной большой потери веса.
В сентябре того же года у Харди случился инсульт, в результате которого он в течение нескольких месяцев не мог разговаривать. Всё это время рядом с ним была его жена Вирджиния, которая постоянно о нём заботилась. В начале августа 1957 года актёр перенёс ещё два инсульта, после чего впал в кому, из которой так и не вышел. Оливер Харди скончался 7 августа 1957 года в возрасте 65 лет.Он был похоронен на мемориальном кладбище в Северном Голливуде. Его вклад в кинематограф был отмечен звездой на Голливудской аллее славы.</p>
<p><b>Интересные факты</b><br>
Оливер Харди снялся более чем в 400 фильмах.
Его любимым занятием была игра в гольф, которой он научился у Ларри Симона.
После его смерти Стэн Лорел дал клятву больше никогда не сниматься, которую, несмотря на многочисленные предложения режиссёров, выполнил.
Лорел и Харди были включены журналом «Entertainment Weekly» в список 45 величайших кинозвёзд всех времён.
В честь Оливера Харди назван астероид (2866) Харди.
Персонаж Оливера Харди в исполнении Джона Фокса появляется в биографическом фильме «Хэрлоу» в 1965 году.
В 1967 году Харди был изображён на обложке альбома The Beatles «Sgt. Pepper’s Lonely Hearts Club Band».
В Италии Оливера Харди озвучивал знаменитый комик Альберто Сорди.
Бен Кортман, вампир из романа Ричарда Матесона «Я — Легенда», по мнению главного героя романа Роберта Невилля, был двойником Оливера Харди.
Оливер Харди был масоном, членом ложи «Соломон» № 20 в Джексонвиле, во Флориде.</p>
            </div>
            <div class="paper__half">
<p><b>Oliver Hardy</b><br>
Oliver Norvell “Babe” Hardy (born Norvell Hardy; January 18, 1892 – August 7, 1957) was an American comic actor famous as one half of Laurel and Hardy, the classic double act that began in the era of silent films and lasted 25 years, from 1927 to 1951. He appeared with his comedy partner Stan Laurel in 107 short films, feature films, and cameo roles. He was credited with his first film, Outwitting Dad, in 1914. In some of his early works, he was billed as “Babe Hardy”, using his nickname.</p>
<p><b>Early life and education</b><br>
Oliver Hardy was born Norvell Hardy in Harlem, Georgia. His father Oliver was a Confederate veteran who had been wounded at the Battle of Antietam on September 17, 1862. After his demobilization as a recruiting officer for Company K, 16th Georgia Regiment, the elder Oliver Hardy assisted his father in running the vestiges of the family cotton plantation. He bought a share in a retail business and was elected full-time Tax Collector for Columbia County, Georgia. Norvell’s mother Emily Norvell was the daughter of Thomas Benjamin Norvell and Mary Freeman, descended from Captain Hugh Norvell of Williamsburg, Virginia, who had arrived in Virginia before 1635. Hardy and Norvell had married March 12, 1890; it was the second marriage for the widow Emily, and the third for Oliver. He was of paternal English American descent and maternal Scottish American descent.
The family moved to Madison in 1891, before Norvell’s birth. Emily Hardy owned a house in Harlem, which was either empty or rented out to tenant farmers. Norvell was likely born in Harlem, though some sources say that his birth occurred in Covington, his mother’s home town. His father died less than a year after his birth. Hardy was the youngest of five children. His older brother Sam Hardy died in a drowning accident in the Oconee River. Hardy pulled his brother from the river but was unable to resuscitate him.
As a child, Hardy was sometimes difficult. He was sent to Georgia Military College in Milledgeville as a youngster. He was sent to Young Harris College in north Georgia in the 1905-1906 school year fall semester (September–January) when he was 13. He was in the junior high component of that institution of the time (the equivalent of high school today).
Hardy had little interest in formal education, although he acquired an early interest in music and theater, possibly from his mother’s tenants. He joined a theatrical group, and later ran away from a boarding school near Atlanta to sing with the group. His mother recognized his talent for singing and sent him to Atlanta to study music and voice with singing teacher Adolf Dahm-Petersen. Hardy skipped some of his lessons to sing in the Alcazar Theater, a cinema, for US$3.50 a week. He subsequently decided to go back to Milledgeville.
Sometime prior to 1910, Hardy began styling himself «Oliver Norvell Hardy», adding the first name «Oliver» as a tribute to his father. He appeared as «Oliver N. Hardy» in the 1910 U.S. census,[N 1] and he used «Oliver» as his first name in all subsequent legal records, marriage announcements, etc.

Hardy was initiated into Freemasonry at Solomon Lodge No. 20 in Jacksonville, Florida. His membership is mentioned in the TV interview on an episode of This Is Your Life in 1954. Hardy’s mother wanted him to attend the University of Georgia in the fall of 1912 to study law, but there is no evidence that he did.
Career</p>
<p><b>Advertisement with Hardy for A Day at School (1916), part of the Plump & Runt series</b><br>
In 1910, when a movie theater opened in Hardy’s home town of Milledgeville, he became the projectionist, ticket taker, janitor and manager. He soon became obsessed with the new motion picture industry, and was convinced that he could do a better job than the actors he saw. A friend suggested that he move to Jacksonville, Florida, where some films were being made. In 1913, Hardy did that, working in Jacksonville as a cabaret and vaudeville singer at night, and at the Lubin Manufacturing Company during the day. It was at this time that he met Madelyn Saloshin, a pianist, whom he married on November 17, 1913 in Macon, Georgia.
The next year he made his first movie, Outwitting Dad (1914), for the Lubin studio. He was billed as O. N. Hardy. In his personal life, he was known as «Babe» Hardy, a nickname that he was given by an Italian barber, who would apply talcum powder to Oliver’s cheeks and say, «nice-a-bab-y.» In many of his later films at Lubin, he was billed as «Babe Hardy.» Hardy was a big man at 6’1» tall and weighing up to 300 pounds. His size placed limitations on the roles he could play. He was most often cast as «the heavy» or the villain. He also frequently had roles in comedy shorts, his size complementing the character.
By 1915, Hardy had made 50 short one-reeler films at Lubin. He later moved to New York and made films for the Pathé, Casino and Edison Studios. After returning to Jacksonville, he made films for the Vim Comedy Company. That studio closed after Hardy discovered the owners were stealing from the payroll.[4] He worked for the King Bee studio, which bought Vim. He worked with Bill Ruge, Billy West (a Charlie Chaplin imitator), and comedic actress Ethel Burton Palmer during this time. (Hardy continued playing the «heavy» for West well into the early 1920s, often imitating Eric Campbell to West’s Chaplin.)
With Stan Laurel in The Lucky Dog (1921), long before they became a team.
In 1917 Hardy moved to Los Angeles, working freelance for several Hollywood studios. Between 1918 and 1923, Hardy made more than 40 films for Vitagraph, mostly playing the «heavy» for Larry Semon. In 1919, he separated from his wife, ending with a provisional divorce in November 1920, which was finalized on November 17, 1921. On November 24, 1921, Hardy married again, to actress Myrtle Reeves. This marriage was also unhappy. Reeves was said to have become alcoholic.
In 1921, he appeared in the movie The Lucky Dog, produced by G.M. («Broncho Billy») Anderson and starring a young British comedian named Stan Laurel.[5] Oliver Hardy played the part of a robber, trying to stick up Stan’s character. They did not work together again for several years. In 1924, Hardy began working at Hal Roach Studios with the Our Gang films and Charley Chase. In 1925, he starred as the Tin Man in the Wizard of Oz. Also that year he was in the film, Yes, Yes, Nanette!, starring Jimmy Finlayson and directed by Stan Laurel. (In later years Finlayson frequently was a supporting actor in the Laurel and Hardy film series.) He also continued playing supporting roles in films featuring Clyde Cooke and Bobby Ray.

In 1926, Hardy was scheduled to appear in Get ‘Em Young. He was unexpectedly hospitalized after being burned by a hot leg of lamb. Laurel, who had been working as a gag man and director at Roach Studios, was recruited to fill in.  Laurel continued to act and, later that year, appeared in the same movie as Hardy, 45 Minutes from Hollywood, although they did not share any scenes together.
Movie poster of Another Fine Mess (1930)
In 1927, Laurel and Hardy began sharing screen time together in Slipping Wives, Duck Soup (no relation to the 1933 Marx Brothers’ film of the same name) and With Love and Hisses. Roach Studios’ supervising director Leo McCarey, realizing the audience reaction to the two, began intentionally teaming them together. This led to the start of a Laurel and Hardy series later that year.
They began producing a huge body of short movies, including The Battle of the Century (1927) (with one of the largest pie fights ever filmed), Should Married Men Go Home? (1928), Two Tars (1928), Unaccustomed As We Are (1929, marking their transition to talking pictures) Berth Marks (1929), Blotto (1930), Brats (1930) (with Stan and Ollie portraying themselves, as well as their own «sons», using oversized furniture sets for the «young» Laurel and Hardy); Another Fine Mess (1930), Be Big! (1931), and many others.
In 1929, they appeared in their first feature, in one of the revue sequences of Hollywood Revue of 1929, and the following year they appeared as the comic relief in a lavish all-color (in Technicolor) musical feature entitled The Rogue Song. This film marked their first appearance in color, yet only a few fragments of this film survive. In 1931, they starred in their first full-length movie, Pardon Us; they continued to make features and shorts until 1935. The Music Box, a 1932 short, won them an Academy Award for best short film — their only such award.
Laurel and Hardy in The Flying Deuces (1939)
In 1936, Hardy and Myrtle Reeves divorced. In 1939, while waiting for a contractual issue between Laurel and Hal Roach to be resolved, Hardy made Zenobia with Harry Langdon. Eventually, however, new contracts were agreed upon and the team was loaned out to producer Boris Morros at General Service Studios to make The Flying Deuces (1939). While on the lot, Hardy fell in love with Virginia Lucille Jones, a script girl, whom he married the next year. They enjoyed a happy marriage until his death.
In 1939, Laurel and Hardy made A Chump at Oxford (1940) (which features a moment of role reversal, with Oliver becoming a subordinate to a temporarily concussed Stan) and Saps at Sea (1940) before leaving Roach Studios. They began performing for the USO, supporting the Allied troops during World War II. They teamed up to make films for 20th Century Fox and later Metro-Goldwyn-Mayer. Although they made more money at the bigger studios, they had very little artistic control; critics say that these films lack the very qualities that had made Laurel and Hardy worldwide names. Their last Fox feature was The Bullfighters (1945), after which they declined to extend their contract with the studio.
In 1947, Laurel and Hardy went on a six-week tour of the United Kingdom. Initially unsure of how they would be received, they were mobbed wherever they went. The tour was lengthened to include engagements in Scandinavia, Belgium, France, as well as a Royal Command Performance for King George VI and Queen Elizabeth. Biographer John McCabe said they continued to make live appearances in the United Kingdom and France for the next several years, until 1954, often using new sketches and material that Laurel had written for them.</p>
<p><b>Oliver Hardy in The Fighting Kentuckian (1949)</b><br>
In 1949, Hardy’s friend, John Wayne, asked him to play a supporting role in The Fighting Kentuckian. Hardy had previously worked with Wayne and John Ford in a charity production of the play What Price Glory? while Laurel began treatment for his diabetes a few years previously. Initially hesitant, Hardy accepted the role at the insistence of his comedy partner. Frank Capra later invited Hardy to play a cameo role in Riding High with Bing Crosby in 1950.
During 1950–51, Laurel and Hardy made their final film. Atoll K (also known as Utopia) was a simple concept; Laurel inherits an island, and the boys set out to sea, where they encounter a storm and discover a brand new island, rich in uranium, making them powerful and wealthy. However, the film was produced by a consortium of European interests, with an international cast and crew that could not speak to each other.[8] In addition, the script needed to be rewritten by Laurel to make it fit the comedy team’s style, and both suffered serious physical illness during the filming.
Oliver Hardy, along with Stan Laurel, made two live television appearances: In 1953, on a live BBC television broadcast of the popular show «Face the Music» with host Henry Hall and in December 1954, on NBC’s This Is Your Life. They also appeared in a filmed insert for the BBC-TV show This Is Music Hall in 1955, their final public appearance together.
Party due to the overwhelmingly positive response to the This Is Your Life telecast, the pair contracted with Hal Roach, Jr., to produce a series of TV shows based on the Mother Goose fables in 1955. According to biographer John McCabe, they were to be filmed in color for NBC, but the series was postponed when Laurel suffered a stroke and required a lengthy convalescence. Later that year while Laurel was recovering, Hardy had a heart attack and stroke from which he never physically recovered.</p>
<p><b>Death</b><br>
Grave of Oliver Hardy, at Valhalla Memorial Park
In May 1954, Hardy suffered a mild heart attack. During 1956, he began looking after his health for the first time in his life. He lost more than 150 pounds in a few months, which completely changed his appearance. Letters written by Laurel refer to Hardy having terminal cancer. Some readers have thought this was the real reason for Hardy’s rapid weight loss. Both men were heavy smokers. Hal Roach said they were a couple of «freight train smoke stacks».
Hardy suffered a major stroke on September 14, 1956, which left him confined to bed and unable to speak for several months. He remained at home, in the care of his beloved Lucille. He suffered two more strokes in early August 1957, and slipped into a coma from which he never recovered. Hardy died from cerebral thrombosis on August 7, 1957, at the age of 65. [N 2] His cremated remains are located in the Masonic Garden of Valhalla Memorial Park Cemetery in North Hollywood. Stan Laurel was too ill to attend the funeral of his friend and film partner,[13] stating, «Babe would understand.»</p>
<p><b>Legacy</b><br>
Statue of Stan Laurel and Oliver Hardy outside the Coronation Hall Theatre, Ulverston, Cumbria, England
Hardy’s star on the Hollywood Walk of Fame is located at 1500 Vine Street, Hollywood, California.
In 1999, merchandiser Larry Harmon produced the direct-to-video film The All New Adventures of Laurel and Hardy: For Love or Mummy, starring Bronson Pinchot and Gailard Sartain as the comedy duo.
There is a small Laurel and Hardy Museum in Hardy’s hometown of Harlem, Georgia, which opened on July 15, 2000. Every year, the first Saturday in October, Oliver Hardy is celebrated and remembered with the Oliver Hardy Festival in this town.
An upcoming film, Stan & Ollie, will see Hardy played by American actor John C. Reilly, and Laurel played by English comedian Steve Coogan. Developed by BBC Films, the film is set in the twilight of their careers, and will focus on their farewell tour of Britain’s variety halls in 1953.</p> 
            </div>
        </div>
    </div>
</template>

<script>
    import Heroes from '../../heroes.js'

    export default { data() { 
        return { names: Heroes.filter(h => h.id === 'hardy')[0].names } 
    } }
</script>