<style lang="scss" scoped>
    @import 'styles.scss';
</style>

<template>
    <div>
        <div class="title">
            <div>{{ names[0] }}\</div>
            <div>\{{ names[1] }}</div>
        </div>
        <div class="paper paper--person">
            <div class="paper__half">
<img src="../../assets/images/heroes/pickford.png">
<p><b>Мэри Пикфорд</b> (англ. Mary Pickford; 8 апреля 1892 — 29 мая 1979), урождённая Глэ́дис Луи́за Смит — знаменитая кино- и театральная актриса канадского происхождения, соосновательница кинокомпании United Artists. Легенда немого кино. Обладательница премии «Оскар» (1930). Прославилась в амплуа девочек-сорванцов и бедных сироток и лишь в последние несколько лет карьеры перешла на «взрослые» роли. Снялась примерно в 250 фильмах.</p>
<p><b>Биография</b><br>
Будущая актриса родилась 8 апреля 1892 года в Торонто, при рождении получив имя Глэдис. Её отец Джон Чарльз Смит был сыном методистов, эмигрировавших в Канаду из Великобритании. Он был разнорабочим, много пил и умер 11 февраля 1898 года от кровоизлияния в мозг, когда служил казначеем на пароходе. Мать, Шарлотта Хеннесси, происходила из семьи ирландских католиков и зарабатывала на жизнь шитьём. У Глэдис были младшие брат и сестра — Джек и Лотти, — которые впоследствии взяли фамилию из её псевдонима и тоже стали актёрами. По решению матери, которая хотела угодить родственникам с обеих сторон, Глэдис прошла обряд крещения в двух церквях — методистской и католической. Тогда же её среднее имя было изменено на Мари.</p>
<p><b>Творческая карьера</b><br>
После смерти мужа Шарлотта, чтобы обеспечить семью, стала держать пансион. По совету одного из постояльцев она ради дополнительного заработка стала играть вместе с детьми в местном театре Princess Theatre. Таким образом 8 января 1900 года семилетняя Глэдис дебютировала на сцене в постановке «Серебряный король». На представлении присутствовали канадские солдаты, призванные в Южную Африку воевать с бурами .
Семья Смитов на протяжении шести лет играла в водевилях и дешёвых мелодрамах. Осенью 1901 года они отправились в Буффало и пять лет гастролировали по Америке, работая на различные театральные компании. В 1907 году пятнадцатилетняя Глэдис добилась аудиенции у продюсера Дэвида Беласко и получила второстепенную роль в пьесе «Уоррены из Вирджинии»  с гонораром в 25 долларов в неделю. По настоянию Беласко она изменила своё достаточно тривиальное имя на псевдоним — Мэри Пикфорд  — и 3 декабря дебютировала на Бродвее. Автором пьесы был Вильям ДеМилль, брат которого Сесил Б. ДеМилль — впоследствии он стал одним из самых именитых кинорежиссёров Голливуда — тоже играл в этом спектакле.</p>
<p><b>Первые годы в кино</b><br>
«Уоррены из Вирджинии» сошли со сцены в октябре 1908 года, выдержав 380 показов, и Мэри осталась без работы. Она считала кинематограф менее значимым искусством, нежели театр, но тем не менее в начале 1909 года обратилась на киностудию Biograph Studios. Режиссёр Д. У. Гриффит устроил девушке пробы и, так как их результаты удовлетворили его, в тот же день снял её в короткометражке. Мэри, которая с самого начала карьеры проявляла деловую хватку, настояла на гонораре в 10 долларов в день, и Гриффит согласился (при том, что обычно платил актёрам вдвое меньшую сумму). В 1909 году он снял актрису более чем в 50 фильмах. Это было обусловлено тем фактом, что производство на заре кинематографа отнимало немного времени — фильмы, занимавшие одну бобину киноплёнки, длились не более 12 минут и зачастую снимались практически без сценария.
Семнадцатилетняя Пикфорд в одном из своих первых фильмов — драме «Одинокая вилла» (1909) с хронометражем всего в 8 минут
В январе 1910 года Гриффит перевёз свою труппу из Нью-Йорка в Лос-Анджелес. Тогда многие кинокомпании проводили зиму на юге западного побережья, так как на северо-восточном светлое время суток становилось короче, и это затрудняло съёмочный процесс. Хотя основной причиной переезда была возможность не платить за грабительские патенты производителей съёмочной техники. Мэри продолжала активно работать, и, хотя в то время на Biograph Studios ещё не существовало титров с перечислением актёров, публика запомнила её, прозвав девочкой с золотыми кудряшками.
В декабре 1910 года Мэри покинула Гриффита и перешла на киностудию Томаса Х. Инса IMP Company, подписав контракт с гонораром в 175 долларов в неделю. Однако качество фильмов (всего более тридцати), снятых на IMP, разочаровало её, и актриса обратилась в суд с требованием разорвать контракт. Выиграв дело, она стала работать на Majestic Film Corp. с ещё большим гонораром в 225 долларов в неделю. Несмотря на то, что кинокомпания приняла в штат в качестве режиссёра её супруга, — актёра Оуэна Мура, за которого Пикфорд вышла в начале года, — их сотрудничество не задалось, и в 1912 году актриса вернулась к Гриффиту. К тому времени она стала широко известна. Пресса все чаще упоминала имя маленькой Мэри  и анонсировала ленты с её участием. Пикфорд завоевала любовь публики благодаря тому, что её игра отличалась интимностью исполнения: актриса выражала эмоции взглядом, а не экспрессивными жестами , и, как писали газеты, вкладывала в игру всё сердце и душу.
В январе 1913 года Пикфорд вернулась на сцену, сыграв в спектакле Беласко под названием «Хорошенький дьяволёнок» (небольшая роль в нём была отведена Лиллиан Гиш, восходящей звезде немого кино). Беласко согласился платить актрисе 250 долларов в неделю, что в 10 раз превышало её гонорар шестилетней давности. Затем продюсер Адольф Цукор предложил Пикфорд экранизировать пьесу. Она согласилась и подписала контракт с его кинокомпанией Famous Players, на этот раз покинув Гриффита окончательно. В 1914 году вышло семь полнометражных фильмов с участием Пикфорд (у Гриффита она снималась только в короткометражках), и в том числе мелодрама «Тэсс из Страны бурь». Роль дочери сквоттера стала поворотным моментом её карьеры. С тех пор кинопоказы фильмов Пикфорд стали сопровождаться такими аншлагами, что газеты советовали зрителям занимать места пораньше, дабы избежать давки .
Сотрудничество Пикфорд и Цукора сложилось невероятно успешно. Появившись за четыре года в двух десятках полнометражных фильмов, актриса превратилась в объект фанатичного обожания публики и настоящую кинозвезду — божественную куколку, воспеваемую поклонниками в стихах . Вслед за популярностью росли и гонорары: к 1916 году Мэри получала 2 тысячи долларов в неделю и половину прибыли от проката.
В тот же период окончательно сложилось её актёрское амплуа, в котором она задержалась на долгие годы. Миловидная внешность Пикфорд — миниатюрное сложение и нежное лицо, обрамлённое завитыми локонами — идеально подходила к типажам её героинь. Преимущественно ими были обездоленные сироты, девочки-подростки бедного происхождения, несправедливо обиженные жизнью девушки. Эти персонажи находили отклик в сердцах публики, вызывая сочувствие и расположение.</p>
<p><b>На вершине славы</b><br>
За пределами съёмочной площадки Пикфорд была не настолько беспомощна, как её героини, и отличалась незаурядными деловыми качествами. В 1916 году она основала собственную кинокомпанию Mary Pickford Company, которая несколько лет функционировала под патронажем Famous Players, и получила почти исключительные права на свои фильмы. Она могла отбирать для себя роли, выбирать по своему усмотрению режиссёров и актёров второго плана, утверждать рекламные кампании своих фильмов и высказывать мнение относительно монтажа. Эта договорённость позволила Пикфорд собрать съёмочную группу, с которой ей было комфортно работать. В частности она наняла режиссёра Маршалла Нилана и оператора Чарльза Рошера, которые были заняты соответственно на восьми и восемнадцати картинах актрисы. Сумма её гонорара поднялась до 10 тысяч долларов в неделю , плюс Пикфорд сохраняла право на половину прибыли от проката.
Из года в год популярность актрисы продолжала расти. Её наиболее кассовыми картинами 1917 и 1918 годов были «Гордость клана» (на одном из сеансов произошло такое столпотворение, что зрители вышибли дверь в кинотеатр) , «Маленькая принцесса», «Звезда морей», «Ребекка с фермы Саннибрук» и «Бедная маленькая богатая девочка». Автором сценариев последних двух лент была Фрэнсис Марион — открытая Пикфорд, она впоследствии написала около полутора десятков сценариев к картинам актрисы и в 1921 году срежиссировала драму с её участием под названием «Свет любви». Героинями Мэри по-прежнему становились девочки-подростки, однако в некоторых картинах — например, в анти-военном фильме «Маленькая американка» и комедии «Вербовка Джоанны» — она играла вполне взрослых девушек.
В 1918 году актриса подписала контракт с First National, обязавшись сняться в трёх картинах с фиксированным гонораром в 675 тысяч долларов — около 10 миллионов долларов в пересчёте по современному курсу. Этими фильмами, производство которых от стадии сценария до финального монтажа она по-прежнему была вправе контролировать, стали «Длинноногий папочка», «Хулиганка» и «Сердце холмов» (вышли в прокат в 1919 году).
В начале 1919 года Пикфорд, Дуглас Фэрбенкс, Чарли Чаплин и Д. У. Гриффит, объединившись, создали собственную кинокомпанию United Artists, которая занималась исключительно прокатом фильмов. Решение основать собственную компанию-дистрибутор было обусловлено стремлением сломать бытовавшую в то время в Голливуде вертикальную схему работы — крупные студии не только контролировали производство фильмов, но и распространение, отдавая их в прокат в сети собственных кинотеатров.
Будучи соучредителем United Artists и продюсером своих фильмов, Пикфорд превратилась в одну из самых влиятельных женщин, когда-либо работавших в киноиндустрии. Первоначально по условиям контракта актриса, равно как и остальные сооснователи, обязалась выпускать по пять фильмов в год. Однако вскоре от этой договоренности пришлось отказаться: производство становилось все более дорогостоящим и длительным процессом. В 1920 году вышло всего две ленты с участием Пикфорд, в 1921 году — три, а затем она окончательно снизила темп и стала выпускать по одному фильму в год.
Первым фильмом Мэри по контракту с United Artists стала трагикомедия «Поллианна», снятая по роману Элеоноры Портер. Эта история о кроткой и добродетельной девочке-сироте пользовалась шумным успехом у публики и собрала в мировом прокате более миллиона долларов . Примечательно, что исключительная добросердечность Поллианны угнетала Пикфорд, которая к тому времени уже начинала уставать от светлых, но достаточно однообразных характеров своих героинь . Общество, впрочем, тогда только приветствовало назидательные сюжеты в кинематографе, а реклама «Поллианны» открыто сообщала, что героиня Пикфорд научит любого, как озарить светом свою жизнь и жизни других .
Далее, после трагикомедии «Мыльная пена», где Мэри сыграла мечтательную прачку-замарашку, последовали драма «Свет любви», комедия «С чёрного хода» и экранизация повести Фрэнсис Барнетт «Маленький лорд Фаунтлерой». Последнему фильму (его вторым режиссёром был брат актрисы Джек Пикфорд) сопутствовали большие сборы в прокате , более того — картина добралась и до послереволюционной России, где была выпущена под названием «Два претендента». В «Маленьком лорде Фаунтлерое» Пикфорд исполнила сразу две роли — юного наследника Седрика Эррола и его матери.
В 1922 году актриса снялась в ремейке собственного хита восьмилетней давности, мелодраме «Тэсс из Страны бурь». Далее она решила рискнуть и реализовать своё давнее желание вырваться из детского амплуа — Пикфорд достигла тридцатилетнего возраста и устала играть викторианских девочек-подростков, кроме того, этот образ постепенно начал выходить из моды . В 1923 году она пригласила к сотрудничеству немецкого режиссёра Эрнста Любича и снялась в его первом американском фильме, мелодраме «Розита». Её героиня, уличная певица Розита, испытавшая на себе бремя любви короля Испании, представляла собой по-настоящему взрослую женщину, но, к сожалению — несмотря на роскошные декорации и прекрасную прессу, которая провозгласила картину очередным триумфом актрисы , — фильм пользовался меньшим успехом, нежели её предыдущие работы.
Поняв, что публика отказывается воспринимать её во взрослом облике, Пикфорд вернулась к былому амплуа. В выпущенном в 1924 году историческом фильме «Дороти Вернон из Хэддон-Холла» она сыграла молодую девушку, в трагикомедии «Маленькая Анни Руни» (1925) — двенадцатилетнюю девочку-сорванца, в драме «Воробушки» (1926) — сироту-подростка. Но тем не менее в следующем 1927 году актрисе исполнилось 35 лет, и она сыграла взрослую роль в мелодраме «Моя любимая девушка».
В марте 1928 года от рака груди умерла мать Пикфорд, и актриса тяжело переживала её смерть. В том же году она решила окончательно порвать с детским имиджем и остригла свои прославленные золотые локоны. При этом событии присутствовали журналисты, и фотографии Пикфорд из парикмахерского салона попали на первые полосы газет.</p>
<p><b>Закат карьеры</b><br>
В 1929 году в свои права начинала вступать эпоха звукового кино, и Пикфорд, разумеется, не могла игнорировать этот факт. Она приобрела права на экранизацию пьесы 1927 года под названием «Кокетка» — это была трагическая история о красавице Норме Безант и её возлюбленном, которого застрелил её отец. Оператором фильма должен был стать давний друг актрисы Чарльз Рошер, однако Пикфорд уволила его, когда тот прервал на середине её сцену. Рошер решил вмешаться в процесс по причине того, что на лицо актрисы легла тень, но тем не менее Пикфорд назначила оператором другого человека . Публика в конечном итоге с восторгом приняла «Кокетку» , а Пикфорд получила за роль Нормы своего первого и единственного «Оскара». Критики, однако, отнеслись к фильму более прохладно .
В 1929 году Пикфорд выпустила ещё один фильм — комедию «Укрощение строптивой» по одноимённому произведению Шекспира, где появилась в паре со своим вторым мужем Дугласом Фэрбенксом. Затем в 1930 году начала производство картины «Твоя навечно», однако из-за пристрастия к алкоголю режиссёра Маршалла Нилана заморозила проект и уничтожила отснятые материалы. Следующая картина Пикфорд, мюзикл «Кики» по мотивам пьесы Беласко, вышла в 1931 году и провалилась в прокате, возместив только половину затраченного бюджета.
Её следующая картина — вестерн 1933 года «Секреты» — тоже не имела кассового успеха. Поэтому Пикфорд решила закончить карьеру и с тех пор более не снималась.</p>
<p><b>Общественная и деловая деятельность</b><br>
Благодаря безграничному доверию, которым Пикфорд пользовалась у публики, она неоднократно принимала участие в различных благотворительных акциях. В 1918 году, когда шла Первая мировая война, актриса совместно с Дугласом Фэрбенксом, Чарли Чаплином и Мэри Дресслер  посетила с публичными выступлениями несколько городов, призывая граждан покупать облигации военного займа — доход от них шёл на финансирование военных нужд.
Когда Пикфорд выступала на Wall Street, её аудитория составила около 50 тысяч человек — несмотря на своё канадское происхождение, она превратилась в один из главных символов Америки тех лет, и благодаря её усилиям в поддержку армии была собрана значительная сумма. Кроме того, совместно с Монти Блю и Джоан Марш она выпустила агитационную короткометражку «Стопроцентные американцы». В то время Пикфорд была очень популярна в армии: в её честь были названы две пушки, 143-й артиллерийский полк носил неофициальное название «Барашки Мэри» , а сама она в феврале 1918 года была возведена в ранг почётного полковника и присутствовала на военных парадах .
В 1921 году Пикфорд совместно с Фэрбенксом, Чаплином и Гриффитом организовала Фонд помощи нуждающимся киноактёрам (функционирует до сих пор) и стала его вице-президентом. Чтобы собрать средства, устроителями проводились благотворительные балы и киносеансы, спортивные мероприятия, показы мод и др. В 1932 году по инициативе Пикфорд фонд обратился к деятелям киноиндустрии, заработок которых превышал 200 долларов в неделю, с просьбой перечислять полпроцента или один процент от своего гонорара в пользу их менее удачливых коллег. 
В 1927 году Пикфорд была в составе влиятельных голливудских лиц, основавших Американскую академию киноискусства. Её соучредителями являлись актёры Дуглас Фэрбенкс и Гарольд Ллойд, режиссёры Фред Нибло и Рауль Уолш, продюсеры Джек Уорнер и Ирвинг Тальберг, а также другие деятели, составлявшие цвет американского кинематографа тех лет.
Затем в 1941 году, уже перестав сниматься в кино, Пикфорд предприняла вторую попытку ослабить влияние крупных студий (в то время монополия на производство и прокат фильмов почти целиком принадлежала MGM, Paramount Pictures, RKO, Warner Bros. и 20th Century Fox) и совместно с Уолтом Диснеем, Орсоном Уэллсом, Чарли Чаплином и другими основала Объединение независимых кинопродюсеров (функционировало до 1958 года).
В 1944 году Мэри стала председателем женского отделения основанного Рузвельтом Национального фонда борьбы с полиомиелитом и посещала госпитали, где лежали больные дети. В 1949 году вместе со своим третьим мужем Чарльзом Роджерсом и другом Малкольмом Бойдом она основала телерадиокомпанию Pickford-Rogers-Boyd.</p>
<p><b>Личная жизнь</b><br>
Актриса трижды была замужем. 7 января 1911 года восемнадцатилетняя Пикфорд вышла замуж за Оуэна Мура, актёра ирландского происхождения, в дуэте с которым часто снималась. Её мать, которая на протяжении многих лет имела большое влияние на Мэри, не разделяла симпатию дочери к Муру, поэтому некоторое время супруги скрывали от неё свои отношения. Их брак оказался неудачным из-за алкоголизма Мура и его неприятия популярности супруги. Начиная с 1914 года они жили раздельно, а затем Пикфорд завязала роман с Дугласом Фэрбенксом — в то время он выступал на Бродвее и вскоре стал столь же знаменит в кино, как и Мэри.
Некоторое время они хранили свою связь в секрете от окружающих. Так как Фэрбенкс был женат, Пикфорд опасалась, что огласка приведет к скандалу, и не хотела портить свою безупречную репутацию. Однако они появлялись вместе на публике во время благотворительных туров 1918 года. 2 марта 1920 года Пикфорд наконец развелась с Муром, и в прессе начали циркулировать слухи о её возможном браке с Фэрбенксом. Несмотря на то, что актриса заявила о беспочвенности подобных слухов , 28 марта она всё-таки вышла за Фэрбенкса (актёр стал свободен ещё в ноябре 1919 года).
Церемония прошла в закрытом кругу — не были приглашены даже их близкие друзья, включая Чаплина, — а свидетелями выступили сводный брат жениха Джон Фэрбенкс и актриса Марджори Доу . 19 мая 1920 года молодожёны отплыли на пароходе Royal George в Европу и провели там всё лето . Осенью 1920 года, вскоре после того, как они вернулись в Америку, имя Пикфорд оказалось косвенно вовлечено в скандал, когда 10 сентября жена её брата Джека, актриса Олив Томас, скончалась во Франции, случайно выпив раствор сулемы (этим лекарством её супруг пытался вылечиться от хронического сифилиса).
После медового месяца звёздная чета поселились вместе в огромном поместье Фэрбенкса неподалеку от Лос-Анджелеса, которое получило название от слияния их имен — Пикфэр. На протяжении 20-х годов Пикфорд и Фэрбенкс составляли самую известную супружескую пару Голливуда. На проводимых в их поместье приёмах собирался цвет артистического, политического и интеллектуального сообществ тех лет. В 1927 году они стали первыми актёрами, которые оставили отпечатки своих ладоней на цементной плите перед входом в кинотеатр Grauman’s Chinese Theate. Слава сопутствовала актёрам по всему миру — и в том числе в СССР.
Летом 1926 года Пикфорд и Фэрбенкс побывали в Советском Союзе, где затем была выпущена книга «Они у нас. Мери Пикфорд и Дуглас Фербенкс в СССР» . Также в 1927 году вышел фильм Сергея Комарова «Поцелуй Мэри Пикфорд». Его производство было само по себе курьёзом: документальные кадры из хроники пребывания актёров на Украине (в частности эпизод, где Мэри поцеловала одного из поклонников) были смонтированы с отснятым уже после их отъезда материалом. В итоге получилась комедия о простом парне Гоге, которому не везёт в любви, но после поцелуя звезды дамы начинают обращать на него внимание. Пикфорд узнала о существовании этого фильма только в конце жизни.
Однако и этот брак актрисы в итоге распался. Из-за плотного съёмочного графика супруги проводили друг с другом немного времени. Помимо этого Фэрбенкс любил путешествовать и начиная с 1930 года уезжал в одиночку, оставляя жену дома. В начале 30-х он увлёкся британской актрисой леди Сильвией Эшли, и этот роман подвёл черту под его браком с Пикфорд. Они стали жить раздельно и развелись 10 января 1936 года. В марте 1936 года Фэрбенкс женился на Эшли. Пикфорд тоже недолго оставалась одна. 24 июня 1937 года она вышла замуж за актёра и джазового музыканта Чарльза «Бадди» Роджерса (своего партнёра в фильме 1927 года «Моя любимая девушка»), но тем не менее сохранила привязанность к Фэрбенксу и, когда в 1939 году он скончался от сердечного приступа, глубоко переживала утрату . В 1943 и 1944 годах Пикфорд и Роджерс усыновили соответственно мальчика Рональда Чарльза и девочку Роксанну. Они прожили вместе более сорока лет до самой смерти актрисы в 1979 году.</p>
<p><b>Последние годы жизни и смерть</b><br>
За Пикфорд долгое время сохранялся статус влиятельного лица в Голливуде — даже после того, как она перестала сниматься. На протяжении 1940-х годов она занималась продюсированием фильмов, выпустив, среди прочих, драму «Спи, моя любовь» (1948) с Клодет Кольбер и комедию «Счастливая любовь» (1949) с братьями Маркс. Её частная жизнь, между тем, была далека от благополучия. За несколько лет она потеряла одного за другим всех своих близких родственников. В 1928 году умерла её мать, в 1933 — брат Джек, в 1936 — сестра Лотти. Болезненное расставание с Фэрбенксом тоже способствовало развитию депрессии, и актриса пристрастилась к алкоголю.
Её приемные дети, повзрослев, рано ушли из дома. Со временем Пикфорд стала вести очень уединённую жизнь и редко покидала Пикфэр, позволяя навещать себя только Лиллиан Гиш, своему пасынку Дугласу Фэрбенксу-младшему и некоторым близким друзьям. В середине 1960-х годов она общалась с внешним миром по телефону, не выходя из спальни. В 1976 году Пикфорд наградили почётным «Оскаром» за вклад в развитие кинематографа, и съёмочная группа, направленная в Пикфэр, запечатлела короткое благодарственное выступление актрисы.
Незадолго до смерти Пикфорд обратилась к правительству Канады с просьбой восстановить её гражданство, которое, как она считала, было утеряно после брака с Фэрбенксом, американским гражданином. Канада удовлетворила просьбу знаменитой соотечественницы, и таким образом на закате жизни у неё появилось двойное гражданство. Мэри Пикфорд — любимица Америки, когда-то обожаемая миллионами — скончалась от кровоизлияния в мозг 29 мая 1979 года в возрасте восьмидесяти семи лет. Она была похоронена на кладбище мемориального парка Форест-Лаун в Калифорнии на том же участке, где покоились её мать, брат и сестра.</p>
            </div>
            <div class="paper__half">
<p><b>Gladys Louise Smith</b> (April 8, 1892 – May 29, 1979), known professionally as Mary Pickford, was a Canadian-American film actress, writer, director, and producer. She was a co-founder of the film studio United Artists and one of the original 36 founders of the Academy of Motion Picture Arts and Sciences. 
Known in her prime as “America’s Sweetheart”   and the “girl with the curls”,  Pickford was one of the Canadian pioneers in early Hollywood and a significant figure in the development of film acting. Pickford was one of the earliest stars to be billed under her name (film performers up until that time were usually unbilled), and was one of the most popular actresses of the 1910s and ‘20s, earning the nickname “Queen of the Movies”.
She was awarded the second ever Academy Award for Best Actress for her first sound film role in Coquette (1929) and also received an honorary Academy Award in 1976. In consideration of her contributions to American cinema, the American Film Institute ranked Pickford as 24th in its 1999 list of greatest female stars of classic Hollywood Cinema.</p>
<p><b>Early life</b><br>
Mary Pickford was born Gladys Louise Smith in 1892 (although she would later claim 1893 or 1894 as her year of birth) at 211 University Avenue,A Toronto, Ontario, Canada.  Her father, John Charles Smith, was the son of English Methodist immigrants, and worked a variety of odd jobs. Her mother, Charlotte Hennessey, was of Irish Catholic descent and worked for a time as a seamstress. She had two younger siblings, Charlotte, called “Lottie” (born 1893), and John Charles, called “Jack” (born 1896), who also became actors. To please her husband’s relatives, Pickford’s mother baptized her children as Methodists, the faith of their father. John Charles Smith was an alcoholic; he abandoned the family and died on February 11, 1898, from a fatal blood clot caused by a workplace accident when he was a purser with Niagara Steamship. 
When Gladys was age four, her household was under infectious quarantine, a public health measure. Their devoutly Catholic maternal grandmother (Catherine Faeley Hennessey) asked a visiting Roman Catholic priest to baptize the children. Pickford was at this time baptized as Gladys Marie Smith. 
Charlotte Smith began taking in boarders after being widowed. One of these was a theatrical stage manager. At his suggestion, Gladys (age 7) was given two small roles, one as a boy and the other as a girl,  in a stock company production of The Silver King at Toronto’s Princess Theatre. She subsequently acted in many melodramas with Toronto’s Valentine Company, finally playing the major child role in their version of The Silver King. She capped her short career in Toronto with the starring role of Little Eva in their production of Uncle Tom’s Cabin, adapted from the 1852 novel by American writer and abolitionist Harriet Beecher Stowe.</p>
<p><b>Career</b><br>
By the early 1900s, theatre had become a family enterprise. Gladys, her mother and two younger siblings toured the United States by rail, performing in third-rate companies and plays. After six impoverished years, Pickford allowed one more summer to land a leading role on Broadway, planning to quit acting if she failed. In 1906 Gladys, Lottie and Jack Smith supported singer Chauncey Olcott on Broadway in Edmund Burke.  Gladys finally landed a supporting role in a 1907 Broadway play, The Warrens of Virginia. The play was written by William C. deMille, whose brother, Cecil, appeared in the cast. David Belasco, the producer of the play, insisted that Gladys Smith assume the stage name Mary Pickford.  After completing the Broadway run and touring the play, however, Pickford was again out of work.
On April 19, 1909, the Biograph Company director D. W. Griffith screen-tested her at the company’s New York studio for a role in the nickelodeon film, Pippa Passes. The role went to someone else but Griffith was immediately taken with Pickford. She quickly grasped that movie acting was simpler than the stylized stage acting of the day. Most Biograph actors earned $5 a day but, after Pickford’s single day in the studio, Griffith agreed to pay her $10 a day against a guarantee of $40 a week. 
Pickford, like all actors at Biograph, played both bit parts and leading roles, including mothers, ingenues, charwomen, spitfires, slaves, Native Americans, spurned women, and a prostitute. As Pickford said of her success at Biograph: “I played scrubwomen and secretaries and women of all nationalities ... I decided that if I could get into as many pictures as possible, I’d become known, and there would be a demand for my work.”
She appeared in 51 films in 1909 – almost one a week. She also introduced her friend Florence La Badie to D. W. Griffith, who launched La Badie’s career. 
In January 1910, Pickford traveled with a Biograph crew to Los Angeles. Many other film companies wintered on the West Coast, escaping the weak light and short days that hampered winter shooting in the East. Pickford added to her 1909 Biographs (Sweet and Twenty, They Would Elope, and To Save Her Soul, to name a few) with films made in California.
Actors were not listed in the credits in Griffith’s company. Audiences noticed and identified Pickford within weeks of her first film appearance. Exhibitors in turn capitalized on her popularity by advertising on sandwich boards that a film featuring “The Girl with the Golden Curls”, “Blondilocks”, or “The Biograph Girl” was inside. 
Pickford left Biograph in December 1910. The following year, she starred in films at Carl Laemmle’s Independent Moving Pictures Company (IMP). IMP was absorbed into Universal Pictures in 1912, along with Majestic. Unhappy with their creative standards, Pickford returned to work with Griffith in 1912. Some of her best performances were in his films, such as Friends, The Mender of Nets, Just Like a Woman, and The Female of the Species. That year Pickford also introduced Dorothy and Lillian Gish (both friends from her days in touring melodrama) to Griffith.  Both became major silent stars, in comedy and tragedy, respectively. Pickford made her last Biograph picture, The New York Hat, in late 1912.
She returned to Broadway in the David Belasco production of A Good Little Devil (1912). This was a major turning point in her career. Pickford, who had always hoped to conquer the Broadway stage, discovered how deeply she missed film acting. In 1913, she decided to work exclusively in film. The previous year, Adolph Zukor had formed Famous Players in Famous Plays. It was later known as Famous Players-Lasky and then Paramount Pictures, one of the first American feature film companies.
Pickford left the stage to join Zukor’s roster of stars. Zukor believed film’s potential lay in recording theatrical players in replicas of their most famous stage roles and productions. Zukor first filmed Pickford in a silent version of A Good Little Devil. The film, produced in 1913, showed the play’s Broadway actors reciting every line of dialogue, resulting in a stiff film that Pickford later called “one of the worst [features] I ever made ... it was deadly”.  Zukor agreed; he held the film back from distribution for a year.
Pickford’s work in material written for the camera by that time had attracted a strong following. Comedy-dramas, such as In the Bishop’s Carriage (1913), Caprice (1913), and especially Hearts Adrift (1914), made her irresistible to moviegoers. Hearts Adrift was so popular that Pickford asked for the first of her many publicized pay raises based on the profits and reviews.  The film marked the first time Pickford’s name was featured above the title on movie marquees.  Tess of the Storm Country was released five weeks later. Biographer Kevin Brownlow observed that the film “sent her career into orbit and made her the most popular actress in America, if not the world”. 
Her appeal was summed up two years later by the February 1916 issue of Photoplay as “luminous tenderness in a steel band of gutter ferocity”.  Only Charlie Chaplin, who reportedly slightly surpassed Pickford’s popularity in 1916,  had a similarly spellbinding pull with critics and the audience. Each enjoyed a level of fame far exceeding that of other actors. Throughout the 1910s and 1920s, Pickford was believed to be the most famous woman in the world, or, as a silent-film journalist described her, “the best known woman who has ever lived, the woman who was known to more people and loved by more people than any other woman that has been in all history.”</p>
<p><b>Stardom</b><br>
Pickford starred in 52 features throughout her career. On June 24, 1916, Pickford signed a new contract with Zukor that granted her full authority over production of the films in which she starred,  and a record-breaking salary of $10,000 a week.  In addition, Pickford’s compensation was half of a film’s profits, with a guarantee of $1,040,000 (US$ 17,150,000 in 2016). Occasionally, she played a child, in films such as The Poor Little Rich Girl (1917), Rebecca of Sunnybrook Farm (1917), Daddy-Long-Legs (1919) and Pollyanna (1920). Pickford’s fans were devoted to these “Little Girl” roles, but they were not typical of her career. 
In August 1918, Pickford’s contract expired and, when refusing Zukor’s terms for a renewal, she was offered $250,000 to leave the motion picture business. She declined, and went to First National Pictures, which agreed to her terms.  In 1919, Pickford, along with D.W. Griffith, Charlie Chaplin, and Douglas Fairbanks, formed the independent film production company United Artists. Through United Artists, Pickford continued to produce and perform in her own movies; she could also distribute them as she chose. In 1920, Pickford’s film Pollyanna grossed around $1,100,000.  The following year, Pickford’s film Little Lord Fauntleroy was also a success, and in 1923, Rosita grossed over $1,000,000 as well.  During this period, she also made Little Annie Rooney (1925), another film in which Pickford played a child, Sparrows (1926), which blended the Dickensian with newly minted German expressionist style, and My Best Girl (1927), a romantic comedy featuring her future husband Buddy Rogers. 
The arrival of sound was her undoing. Pickford underestimated the value of adding sound to movies, claiming that “adding sound to movies would be like putting lipstick on the Venus de Milo”. 
She played a reckless socialite in Coquette (1929), a role for which her famous ringlets were cut into a 1920s’ bob. Pickford had already cut her hair in the wake of her mother’s death in 1928. Fans were shocked at the transformation.  Pickford’s hair had become a symbol of female virtue, and when she cut it, the act made front-page news in The New York Times and other papers. Coquette was a success and won her an Academy Award for Best Actress,  although this was highly controversial.  The public failed to respond to her in the more sophisticated roles. Like most movie stars of the silent era, Pickford found her career fading as talkies became more popular among audiences. 
Her next film, The Taming of The Shrew, made with husband Douglas Fairbanks, was not well received at the box office.  Established Hollywood actors were panicked by the impending arrival of the talkies. On March 29, 1928, The Dodge Brothers Hour was broadcast from Pickford’s bungalow, featuring Fairbanks, Chaplin, Norma Talmadge, Gloria Swanson, John Barrymore, D.W. Griffith, and Dolores del Rio, among others. They spoke on the radio show to prove that they could meet the challenge of talking movies. 
But the transition came as Pickford was in her late 30s, no longer able to play the children, teenage spitfires, and feisty young women so adored by her fans, and was not suited for the glamorous and vampish heroines of early sound. In 1933, Pickford underwent a Technicolor screen test for an animated/live action film version of Alice in Wonderland, but Walt Disney discarded the project when Paramount released its own version of the book. Only one Technicolor still of her screen test still exists. She retired from acting in 1933; her last acting film was released in 1934. She continued to produce for others, however, including Sleep, My Love (1948; with Claudette Colbert) and Love Happy (1949), with the Marx Brothers). </p>
<p><b>The film industry</b><br>
Mary Pickford giving President Herbert Hoover a ticket for a film industry benefit for the unemployed, 1931
Pickford used her stature in the movie industry to promote a variety of causes. Although her image depicted fragility and innocence, Pickford proved to be a worthy businesswoman who took control of her career in a cutthroat industry. 
During World War I, she promoted the sale of Liberty Bonds, making an intensive series of fund-raising speeches that kicked off in Washington, D.C., where she sold bonds alongside Charles Chaplin, Douglas Fairbanks, Theda Bara, and Marie Dressler. Five days later she spoke on Wall Street to an estimated 50,000 people. Though Canadian-born, she was a powerful symbol of Americana, kissing the American flag for cameras and auctioning one of her world-famous curls for $15,000. In a single speech in Chicago she sold an estimated five million dollars’ worth of bonds. She was christened the U.S. Navy’s official “Little Sister”; the Army named two cannons after her and made her an honorary colonel. 
At the end of World War I, Pickford conceived of the Motion Picture Relief Fund, an organization to help financially needy actors. Leftover funds from her work selling Liberty Bonds were put toward its creation, and in 1921, the Motion Picture Relief Fund (MPRF) was officially incorporated, with Joseph Schenck voted its first president and Pickford its vice president. In 1932, Pickford spearheaded the “Payroll Pledge Program”, a payroll-deduction plan for studio workers who gave one half of one percent of their earnings to the MPRF. As a result, in 1940, the Fund was able to purchase land and build the Motion Picture Country House and Hospital, in Woodland Hills, California. 
An astute businesswoman, Pickford became her own producer within three years of her start in features. According to her Foundation, “she oversaw every aspect of the making of her films, from hiring talent and crew to overseeing the script, the shooting, the editing, to the final release and promotion of each project.” She demanded (and received) these powers in 1916, when she was under contract to Zukor’s Famous Players In Famous Plays (later Paramount). Zukor acquiesced to her refusal to participate in block-booking, the widespread practice of forcing an exhibitor to show a bad film of the studio’s choosing to also be able to show a Pickford film. In 1916, Pickford’s films were distributed, singly, through a special distribution unit called Artcraft. The Mary Pickford Corporation was briefly Pickford’s motion-picture production company. 
In 1919, she increased her power by co-founding United Artists (UA) with Charlie Chaplin, D. W. Griffith, and her soon-to-be husband, Douglas Fairbanks. Before UA’s creation, Hollywood studios were vertically integrated, not only producing films but forming chains of theaters. Distributors (also part of the studios) arranged for company productions to be shown in the company’s movie venues. Filmmakers relied on the studios for bookings; in return they put up with what many considered creative interference.
United Artists broke from this tradition. It was solely a distribution company, offering independent film producers access to its own screens as well as the rental of temporarily unbooked cinemas owned by other companies. Pickford and Fairbanks produced and shot their films after 1920 at the jointly owned Pickford-Fairbanks studio on Santa Monica Boulevard. The producers who signed with UA were true independents, producing, creating and controlling their work to an unprecedented degree. As a co-founder, as well as the producer and star of her own films, Pickford became the most powerful woman who has ever worked in Hollywood. By 1930, Pickford’s acting career had largely faded.  After retiring three years later, however, she continued to produce films for United Artists. She and Chaplin remained partners in the company for decades. Chaplin left the company in 1955, and Pickford followed suit in 1956, selling her remaining shares for three million dollars.</p>
<p><b>Personal life</b><br>
Pickford was married three times. She married Owen Moore, an Irish-born silent film actor, on January 7, 1911. It is rumored she became pregnant by Moore in the early 1910s and had a miscarriage or an abortion. Some accounts suggest this resulted in her later inability to have children.  The couple had numerous marital problems, notably Moore’s alcoholism, insecurity about living in the shadow of Pickford’s fame, and bouts of domestic violence. The couple lived together on-and-off for several years. 
Pickford became secretly involved in a relationship with Douglas Fairbanks. They toured the US together in 1918 to promote Liberty Bond sales for the World War I effort. Around this time, Pickford also suffered from the flu during the 1918 flu pandemic, but survived.  Pickford divorced Moore on March 2, 1920, after she agreed to his $100,000 demand for a settlement.  She married Fairbanks just days later on March 28, 1920. They went to Europe for their honeymoon; fans in London and in Paris caused riots trying to get to the famous couple. The couple’s triumphant return to Hollywood was witnessed by vast crowds who turned out to hail them at railway stations across the United States.
The Mark of Zorro (1920) and a series of other swashbucklers gave the popular Fairbanks a more romantic, heroic image. Pickford continued to epitomize the virtuous but fiery girl next door. Even at private parties, people instinctively stood up when Pickford entered a room; she and her husband were often referred to as “Hollywood royalty”. Their international reputations were broad. Foreign heads of state and dignitaries who visited the White House often asked if they could also visit Pickfair, the couple’s mansion in Beverly Hills. 
Dinners at Pickfair included a number of notable guests. Charlie Chaplin, Fairbanks’ best friend, was often present. Other guests included George Bernard Shaw, Albert Einstein, Elinor Glyn, Helen Keller, H. G. Wells, Lord Mountbatten, Fritz Kreisler, Amelia Earhart, F. Scott Fitzgerald, Noël Coward, Max Reinhardt, Baron Nishi, Vladimir Nemirovich-Danchenko,  Sir Arthur Conan Doyle, Austen Chamberlain, Sir Harry Lauder, and Meher Baba, among others. The public nature of Pickford’s second marriage strained it to the breaking point. Both she and Fairbanks had little time off from producing and acting in their films. They were also constantly on display as America’s unofficial ambassadors to the world, leading parades, cutting ribbons, and making speeches. When their film careers both began to flounder at the end of the silent era, Fairbanks’ restless nature prompted him to overseas travel (something which Pickford did not enjoy). When Fairbanks’ romance with Sylvia, Lady Ashley became public in the early 1930s, he and Pickford separated. They divorced January 10, 1936. Fairbanks’ son by his first wife, Douglas Fairbanks Jr., claimed his father and Pickford long regretted their inability to reconcile. 
On June 24, 1937, Pickford married her third and last husband, actor and band leader Buddy Rogers. They adopted two children: Roxanne (born 1944, adopted 1944) and Ronald Charles (born 1937, adopted 1943, a.k.a. Ronnie Pickford Rogers). As a PBS American Experience documentary noted, Pickford’s relationship with her children was tense. She criticized their physical imperfections, including Ronnie’s small stature and Roxanne’s crooked teeth. Both children later said their mother was too self-absorbed to provide real maternal love. In 2003, Ronnie recalled that “Things didn’t work out that much, you know. But I’ll never forget her. I think that she was a good woman.”</p>
<p><b>Later years</b><br>
After retiring from the screen, Pickford became an alcoholic, as her father had been. Her mother Charlotte died of breast cancer in March 1928. Her siblings, Lottie and Jack, both died of alcohol-related causes. These deaths, her divorce from Fairbanks, and the end of silent films left Pickford deeply depressed. Her relationship with her children, Roxanne and Ronald, was turbulent at best. Pickford withdrew and gradually became a recluse, remaining almost entirely at Pickfair and allowing visits only from Lillian Gish, her stepson Douglas Fairbanks, Jr., and few other people. She appeared in court in 1959, in a matter pertaining to her co-ownership of North Carolina TV station WSJS-TV. The court date coincided with the date of her 67th birthday; under oath, when asked to give her age, Pickford replied, “I’m 21, going on 20”. 
In the mid-1960s, Pickford often received visitors only by telephone, speaking to them from her bedroom. Buddy Rogers often gave guests tours of Pickfair, including views of a genuine western bar Pickford had bought for Douglas Fairbanks, and a portrait of Pickford in the drawing room. A print of this image now hangs in the Library of Congress.  In addition to her Oscar as best actress for Coquette (1929), Mary Pickford received an Academy Honorary Award in 1976 for lifetime achievement. The Academy sent a TV crew to her house to record her short statement of thanks – offering the public a very rare glimpse into Pickfair Manor. 
Pickford had become an American citizen upon her marriage to Fairbanks in 1920.  Toward the end of her life, Pickford made arrangements with the Department of Citizenship to regain her Canadian citizenship because she wished to “die as a Canadian”. Her request was approved and she became a dual Canadian-American citizen.</p>
<p><b>Death</b><br>
On May 29, 1979, Pickford died at a Santa Monica, California hospital of complications from a cerebral hemorrhage she had suffered the week before.  She was interred in the Garden of Memory of the Forest Lawn Memorial Park cemetery in Glendale, California.  Buried alongside her in the Pickford private family plot are her mother Charlotte, her siblings Lottie and Jack Pickford, and the family of Elizabeth Watson, Charlotte’s sister, who had helped raise Pickford in Toronto.</p>
            </div>
        </div>
    </div>
</template>

<script>
    import Heroes from '../../heroes.js'

    export default { data() { 
        return { names: Heroes.filter(h => h.id === 'pickford')[0].names } 
    } }
</script>