<style lang="scss" scoped>
    @import 'styles.scss';
</style>

<template>
    <div :class="'paper paper--' + $route.params.lang">
        <div class="paper__page">
            <div class="paper__illustrations">
                <img src="../../assets/images/kinetoscope/Kinetoscope.jpg">
                <img src="../../assets/images/kinetoscope/800px-Optic_Projection_fig_221.jpg">
            </div>
            <div v-if="$route.params.lang === 'ru'">
<p><b>Кинетоскоп</b><br> (англ. kinetoscope) (от греческого «кинетос» — движущийся и «скопео» — смотреть) — ранняя технология кинематографа для показа движущегося изображения, изобретённая в 1888 году Томасом Эдисоном. В отличие от современного кинопроектора кинетоскоп не давал возможности коллективного просмотра на экране, а был предназначен для индивидуального зрителя, наблюдавшего изображение через окуляр.</p>
<p><b>Принцип действия</b><br>
Кинетоскоп представлял из себя деревянный ящик, внутри которого была натянута на роликах киноплёнка, непрерывно движущаяся мимо окуляра, расположенного на верхней крышке аппарата. Смазывание изображения, наблюдаемого через окуляр на освещённой электролампой киноплёнке, предотвращалось обтюратором с малым углом раскрытия. Эдисон планировал также создать кинетоскоп для просмотра объёмных изображений по аналогии с появившимся стереоскопом, но из-за начавшейся конкуренции с другими устройствами, вскоре отказался от этой идеи. Одним из главных недостатков конструкции, обусловившим индивидуальный способ просмотра, была низкая световая эффективность. Из-за непрерывного движения киноплёнки мимо окуляра, кинетоскоп требовал очень коротких вспышек света для получения хотя бы относительной устойчивости изображения. Это лишало возможности обеспечить достаточную яркость при проекции на экран. Предпринятые после первых успехов аппарата Эдисона многочисленные попытки других изобретателей усовершенствовать его, увенчались появлением «Синематографа» братьев Люмьер, в котором плёнка двигалась прерывисто при помощи грейфера. Акционерное общество «Кинетоскоп» снимало фильмы для своих аппаратов с помощью «Кинетографа», но для просмотра впоследствии оказались пригодны также киноролики, снятые другими устройствами. Формат 35-мм киноплёнки, впервые разработанный Эдисоном для кинетоскопа, быстро стал всеобщим стандартом и позволил осуществлять обмен фильмами, изготовленными различными аппаратами. В момент появления технологии теоретических обоснований частоты съёмки и проекции ещё не существовало, поэтому скорость киноплёнки варьировалась в аппаратах в пределах 30 — 40 кадров в секунду. При просмотре, благодаря инерции зрения, создавалось впечатление движущегося изображения. Ролик киноплёнки «Кодак-Эдисон» стандартной длины 50 футов при частоте показа 40 кадров в секунду имел продолжительность не более 20 секунд. Некоторые фильмы снимались и демонстрировались при пониженной частоте, поскольку киноплёнка большей длины не выпускалась. Считается, что ролик про атлета Сандова из «первой десятки» кинопроката Эдисона был снят со скоростью 16 кадров в секунду, чтобы удлинить время просмотра до 50 секунд.</p>
<p><b>Коммерческое использование</b><br>
Патентную заявку на изобретение Эдисон подал 31 июля 1891 года, хотя аппарат ещё находился на стадии лабораторных испытаний и не был готов для серийного производства. Незадолго до этого — 20 мая — в лаборатории состоялась первая публичная демонстрация изготовленного прототипа для 150 участниц Федерации женских клубов США. Показанный ролик впоследствии получил название «Приветствие Диксона». Восторг публики, впервые увидевшей движущиеся фотографии, убедил авторов изобретения в целесообразности его коммерческого использования. В 1892 году было создано «Акционерное общество Кинетоскоп», получившее монополию на распространение аппаратов и технологии на территории США.
14 марта 1893 года патент на «Кинетоскоп» был получен и вскоре аппарат экспонировался на выставке в Чикаго. 9 мая состоялась первая демонстрация серийного устройства в Институте Искусства и Науки в Бруклине. Первым фильмом, представленным публике стала «Сцена с кузнецами», снятая в новой студии. Последним штрихом была установка на кинетоскопах автоматического монетоприёмника: так Эдисон, проделавший до этого то же самое с фонографом, оказался одним из изобретателей торговых автоматов. 14 апреля 1894 года коммерсанты братья Холланд открыли на Бродвее «кабину» (англ. Kinetoscope Parlor), в которой были установлены десять кинетоскопов, предназначенных для индивидуального просмотра. Аппараты, установленные по пять штук в два ряда, показывали разные фильмы, и каждый зритель за 25 центов мог посмотреть ролики одного ряда, а за полдоллара — все десять. Кинетоскопы были куплены у лабораторий Эдисона по цене 200 долларов за штуку акционерным обществом во главе с Норманом Раффом и Фрэнком Гаммоном, компаньоном которых стал Эндрю Холланд, один из владельцев кинозала. В первую программу вошли десять фильмов: «Парикмахерская», «Кузнецы», «Петушиный бой», «Подковывание лошади», «Горные танцы», «Трапеция», «Борьба», два ролика о британской акробатке Эне Бертольди и один об упражнениях атлета Сандова. К 1 июня Холланды открыли аналогичные заведения в Чикаго и Сан-Франциско, а 17 октября появился первый зал за пределами США — в Лондоне. В акционерное общество начали вступать десятки новых компаний, желающих распространять аттракцион, приносящий немедленную прибыль. Только за 11 первых месяцев эксплуатации кинетоскопы принесли доход в размере 150 тысяч долларов.
Уже за полтора года до первой демонстрации фильма Люмьерами на большом экране в парижском «Гран-кафе», Эдисон положил начало кинопрокату, создав целую сеть кинозалов. Кинетоскопы быстро стали популярны у публики, но рассматривание изображения через окуляр не отвечало нынешним представлениям о кинозрелище, подразумевающим одновременный просмотр несколькими зрителями. Кроме того, большинство сюжетов были примитивны и повторяли тематику, общепринятую для зоотропов. Каталог кинороликов для кинетоскопа, насчитывавший в конце 1894 года 60 наименований, в основном состоял из фильмов о дрессированных животных, акробатах, танцах и борьбе. Все фильмы имели стандартную длину 50 футов и снимались с таким расчётом, чтобы сюжет мог быть склеен в кольцо, повторяясь бесконечно. В результате, аппарат за счёт многопетельного лентопротяжного тракта не требовал перезарядки. Одним из самых известных роликов стал «Танец Лои Фуллер», который считается первым в истории колоризованным фильмом. В июле 1894 года зафиксирован первый случай киноцензуры: владелец зала в Сан-Франциско был арестован на месяц за «неприличный киносеанс», во время которого демонстрировался фильм «Карменсита». Однако, подобные инциденты не помешали появлению роликов, специально отснятых для залов с табличкой «Только для мужчин»: в этих фильмах, пользовавшихся большим успехом, хористки задирали юбки, танцуя канкан.</p>
<p><b>Проецирующий кинетоскоп</b><br>
Успешная экспансия «Синематографа» сделала очевидной необходимость создания собственной технологии, позволяющей получать изображение на экране. Появившийся позднее «Мутоскоп», несмотря на сходный метод индивидуального просмотра через окуляр, оказался дешевле и удачнее кинетоскопа, предопределив его коммерческий провал. Поэтому, уже в 1895 году Эдисон под маркой «Витаско́п» (англ. Vitascope) начал продавать созданное Чарльзом Дженкинсоном (англ. Charles Francis Jenkins) и Томасом Арматом (англ. Thomas Armat) устройство для проекции фильмов на большие экраны. В процессе эксплуатации выявился ряд недостатков этих кинопроекторов, заставивших Эдисона предпринять усилия для собственных разработок. В результате с ноября 1896 года компания приступила к выпуску нового устройства для проекции фильмов «Проджектоскоп» (англ. Projectoscope).
В 1912 году Эдисон выпустил на рынок «Проджектоскоп» для любительского использования в домашних условиях. На негорючей киноплёнке нового формата шириной 22-мм для такого проджектоскопа изображение располагалось на трёх дорожках кадров размером 4×6 мм. Проекция происходила последовательно с реверсом механизма: сначала при прямом ходе проецировался первый ряд, затем при обратном — второй, расположенный в середине, и в конце — третий снова в прямом направлении. Технология не получила распространения, уступая в удобстве появившимся двумя годами ранее 28-мм любительским проекторам «Pathé KOK». Через четыре года компания Эдисона вышла на рынок со своей последней технологией кинопроекции «Супер Кинетоскоп», так же не получившей распространения из-за жёсткой конкуренции с более удачными проекторами.</p>
<p><b>Кинетофон</b><br>
Идея создания устройства, способного воспроизводить звук одновременно с изображением, появилась раньше, чем начались разработки кинетографа и кинетоскопа, задуманных Эдисоном, как приставка к изобретённому им ранее фонографу. В 1894 году он писал:

В 1887 году мне пришла мысль о возможности сконструировать аппарат, который будет для зрения тем же, чем является фонограф для слуха, и который будет и записывать и воспроизводить одновременно звук и движение

В марте 1895 года завершено создание аппарата, представляющего из себя помещённые в один корпус кинетоскоп и фонограф с общим приводом лентопротяжного механизма и звукового цилиндра под названием «Кинетофон» (англ. kinetophone)[17]. Первым известным звуковым фильмом является снятая в 1894 году или в самом начале 1895 года на студии Эдисона в Уэст-Орандже запись, ныне известная как «Экспериментальный звуковой фильм Диксона». Синхронная съёмка фильмов для кинетофона была затруднена по многим причинам, главными из которых были низкая чувствительность мембраны фонографа и необходимость использования громоздких рупоров, неизбежно видимых в кадре, как в упомянутом фильме. Точность синхронизации оставалась низкой, исключая совпадение артикуляции с речевой фонограммой. Поэтому большинство звуковых кинороликов представляли собой ритмические действия, происходящие под музыку, записанную отдельно от изображения. Демонстраторы могли подобрать к каждому фильму звуковое сопровождение из широкого спектра поставлявшихся валиков фонографа, задавая подходящий темп. Невысокая громкость допускала только индивидуальное прослушивание звука через первые в мире внутриканальные наушники, что хорошо сочеталось с конструкцией кинетоскопа, но было неприемлемо при проекции на большой экран. В результате, кинетофон устарел одновременно с кинетоскопом, вытесненным с рынка кинопроекторами различных систем. Было выпущено не более двух-трёх дюжин аппаратов, не имевших коммерческого успеха.
Дальнейшие попытки объединить изображение со звуком предпринимались уже с проецирующим кинетоскопом. В 1913 году технология была продемонстрирована за пределами США, в том числе в Москве и Санкт-Петербурге, где была встречена неоднозначно. Однако, на тот момент уже существовала аналогичная система звукового кино «Гомон Хронофон» компании Gaumont, использующая более современные грампластинки вместо устаревших валиков.</p>
            </div>
            <div v-if="$route.params.lang === 'en'">
<p><b>Kinetoscope</b><br>
The Kinetoscope is an early motion picture exhibition device. The Kinetoscope was designed for films to be viewed by one individual at a time through a peephole viewer window at the top of the device. The Kinetoscope was not a movie projector, but introduced the basic approach that would become the standard for all cinematic projection before the advent of video, by creating the illusion of movement by conveying a strip of perforated film bearing sequential images over a light source with a high-speed shutter. A process using roll film first described in a patent application submitted in France and the U.S. by French inventor Louis Le Prince, the concept was copied by U.S. inventor Thomas Edison in 1889, and subsequently developed by his employee William Kennedy Laurie Dickson between 1889 and 1892.[1] Dickson and his team at the Edison lab also devised the Kinetograph, an innovative motion picture camera with rapid intermittent, or stop-and-go, film movement, to photograph movies for in-house experiments and, eventually, commercial Kinetoscope presentations.
A prototype for the Kinetoscope was shown to a convention of the National Federation of Women's Clubs on May 20, 1891. The first public demonstration of the Kinetoscope was held at the Brooklyn Institute of Arts and Sciences on May 9, 1893. Instrumental to the birth of American movie culture, the Kinetoscope also had a major impact in Europe; its influence abroad was magnified by Edison's decision not to seek international patents on the device, facilitating numerous imitations of and improvements on the technology. In 1895, Edison introduced the Kinetophone, which joined the Kinetoscope with a cylinder phonograph. Film projection, which Edison initially disdained as financially nonviable, soon superseded the Kinetoscope's individual exhibition model. Many of the projection systems developed by Edison's firm in later years would use the Kinetoscope name.</p>
<p><b>Projecting Kinetoscopes</b><br>
Over the course of 1895, it became clear that the Kinetoscope was going to lose out on one end to projected motion pictures and, on the other, to a new "peep show" device, the cheap, flip-book-based Mutoscope. In its second year of commercialization, the Kinetoscope operation's profits plummeted by more than 95 percent, to just over $4,000. The Latham brothers and their father, Woodville, had retained the services of former Edison employee Eugene Lauste and then, in April 1895, Dickson himself to develop a film projection system. On May 20, in New York City, the new Eidoloscope was used for the first commercial screening of a motion picture: a boxing match between Young Griffo and Charles Barnett, four or eight minutes long. European inventors, most prominently the Lumières and Germany's Skladanowsky brothers, were moving forward with similar systems.
By the beginning of 1896, Edison had turned his attention to promoting a projector technology, the Phantoscope, developed by young inventors Charles Francis Jenkins and Thomas Armat. The rights to the system had been acquired by Raff and Gammon, who redubbed it the Vitascope and arranged with Edison to present himself as its creator.  With Dickson having left his employ, the Kinetophone was soon mothballed and Edison suspended work on sound cinema for an extended period. Departing the Vitascope operation after little more than a year, Edison commissioned the development of his own projection systems, the Projectoscope and then multiple iterations of the Projecting Kinetoscope. In 1912, he introduced the ambitious and expensive Home Projecting Kinetoscope, which employed a unique format of three parallel columns of sequential frames on one strip of film—the middle column ran through the machine in the reverse direction from its neighbors. It was a commercial failure. Four years later, the Edison operation came out with its last substantial new film exhibition technology, a short-lived theatrical system called the Super Kinetoscope. Much of the Edison company's most creative work in the motion picture field from 1897 on involved the use of Kinetoscope-related patents in threatened or actual lawsuits for the purpose of financially pressuring or blocking commercial rivals. 
As far back as the Vitascope days, some exhibitors had screened films accompanied by phonographs playing appropriate, though very roughly timed, sound effects; in the style of the Kinetophone described above, rhythmically matching recordings were also made available for march and dance subjects. While Edison oversaw cursory sound-cinema experiments after the success of The Great Train Robbery (1903) and other Edison Manufacturing Company productions, it was not until 1908 that he returned in earnest to the combined audiovisual concept that had first led him to enter the motion picture field. Edison patented a synchronization system connecting a projector and a phonograph, located behind the screen, via an assembly of three rigid shafts—a vertical one descending from each device, joined by a third running horizontally the entire length of the theater, beneath the floor. Two years later, he supervised a press demonstration at the laboratory of a sound-film system of either this or a later design. In 1913, Edison finally introduced the new Kinetophone—like all of his sound-film exhibition systems since the first in the mid-1890s, it used a cylinder phonograph, now connected to a Projecting Kinetoscope via a fishing line–type belt and a series of metal pulleys. While it met with great acclaim in the short term, poorly trained operators had trouble keeping picture in synchronization with sound and, like other sound-film systems of the era, the Kinetophone had not solved the issues of insufficient amplification and unpleasant audio quality. Its drawing power as a novelty soon faded and when a fire at Edison's West Orange complex in December 1914 destroyed all of the company's Kinetophone image and sound masters, the system was abandoned.</p>
            </div>
        </div>
    </div>
</template>

<script>
    export default {}
</script>
